apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      restartPolicy: Always
      containers:
        - name: nodejs
          image: amiralamti/node:amira
          ports:
            - containerPort: 3005


