apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: deploy
spec:
  type:  NodePort
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  selector :
    app: deploy
